elections/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'elections'

urlpatterns = [
                  # /home/
                  url(r'^$', views.home, name='home'),
                  url(r'^templates/hashtags/$', views.hashtags, name='hashtags'),
                  url(r'^templates/retweets/$', views.retweets, name='retweets'),
                  url(r'^templates/popularity/$', views.popularity, name='popularity'),
                  url(r'^templates/location/$', views.location, name='location'),
                  url(r'^templates/analysis/$', views.analysis, name='analysis'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tango/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^elections/', include('elections.urls')),
]

elections/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

elections/views.py
from django.http import HttpResponse
from django.template import loader

def home(request):
	template = loader.get_template('elections/home.html')
	return HttpResponse (template.render(request))

def hashtags(request):
	template=loader.get_template('elections/hashtags.html')
	return HttpResponse(template.render(request))

def retweets(request):
	template=loader.get_template('elections/retweets.html')
	return HttpResponse(template.render(request))

def popularity(request):
	template=loader.get_template('elections/popularity.html')
	return HttpResponse(template.render(request))

def location(request):
	template=loader.get_template('elections/location.html')
	return HttpResponse(template.render(request))

def analysis(request):
	template=loader.get_template('elections/analysis.html')
	return HttpResponse(template.render(request))

elections/templates/elections/analysis.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Averia+Libre|Cormorant+Upright" rel="stylesheet" >
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <title>Analysis</title>
</head>

<body>
<link rel="stylesheet" type="text/css" href="{% static 'elections/style2.css' %}" />

<nav class="navbar navbar-inverse">
<div class="container-fluid">

<!--Header-->
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand mb-0">
  <img src="http://vignette4.wikia.nocookie.net/simpsons/images/1/11/Twitter_bird_icon.png/revision/latest?cb=20111228065136" width="50" height="40" class="d-inline-block align-top" alt="Twitter">
      #USElections2016
      </a>
<!--ITEMS-->

<div class="collapse navbar-collapse" id="topNavBar">
	<ul class="nav navbar-nav navbar-right">

        <li class="">
					<a href="{% url 'elections:hashtags' %}">Popular hashtags
						<span class="glyphicon glyphicon-equalizer" aria-hidden="true"></span>&nbsp
					</a>
			</li>

         <li class="">
					<a href="{% url 'elections:popularity' %}">Who is more popular?
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp
					</a>
			</li>

         <li class="">
					<a href="{% url 'elections:retweets' %}">Distribution of tweets
						<span class="glyphicon glyphicon-retweet" aria-hidden="true"></span>&nbsp
					</a>
			</li>

         <li class="">
					<a href="{% url 'elections:location' %}">Location
						<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>&nbsp
					</a>
			</li>
        <li class="">
					<a href="{% url 'elections:home' %}">Home
						<span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp
					</a>
			</li>


	</ul>
</div>
</div>
</nav>
<center>
    <br>
<h2><b>Total tweets collected : 22180 <br>
Database used : MongoDB <br>
Aid : Twitter Streaming API <br>
Hashtags used : #USelections, #Clinton , #Trump<br>
</center>
</h2>
</body>

<body>
	<style>
      body {
        font-family: 'Cormorant Upright', serif;
        font-size: 20px;
      }
    </style>
</body>



</body>
</html>

elections/templates/elections/hashtags.html
<!DOCTYPE html>
<html>
<head>
     <meta charset="utf-8" />
     {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Averia+Libre|Cormorant+Upright" rel="stylesheet" >
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

        <link href="https://www.highcharts.com/highslide/highslide.css" rel="stylesheet" />
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/highcharts-more.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/modules/heatmap.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/modules/exporting.js"></script>

	<title>Hashtags</title>
</head>

<body>
<link rel="stylesheet" type="text/css" href="{% static 'elections/style2.css' %}" />

<nav class="navbar navbar-inverse">
<div class="container-fluid">

<!--Header-->
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand mb-0">
  <img src="http://vignette4.wikia.nocookie.net/simpsons/images/1/11/Twitter_bird_icon.png/revision/latest?cb=20111228065136" width="50" height="40" class="d-inline-block align-top" alt="Twitter">
      #USElections2016
      </a>
<!--ITEMS-->

<div class="collapse navbar-collapse" id="topNavBar">
	<ul class="nav navbar-nav navbar-right">
			<li class="">
					<a href="{% url 'elections:analysis' %}">Back
						<span class="glyphicon glyphicon-hand-left" aria-hidden="true"></span>&nbsp
					</a>
			</li>

			<li class="">
					<a href="{% url 'elections:home' %}">Home
						<span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp
					</a>
			</li>
	</ul>
</div>
</div>
</div>
</nav>
</body>

<body style="margin:0;padding:0">
                <div id="container" style="">Loading....</div>


    <script>
        $(function(){
            Highcharts.setOptions({"lang": {}, "global": {}});
            var option = {"loading": {}, "subtitle": {}, "xAxis": {"categories": ["#USelections", "#trump/Donaldtrump", "#clinton/hillaryclinton", "#FBI", "#WorldSeries", "#postseason", "#Comey", "#Breaking", "#MAGA", "#AP"], "title": {"text": "Hashtags"}}, "title": {"text": "Top 10 popular hashtags"}, "series": {}, "labels": {}, "chart": {"renderTo": "container", "type": "line"}, "tooltip": {}, "plotOptions": {}, "yAxis": {"title": {"text": "Occurrence"}}, "credits": {"enabled": false}, "colors": {}, "pane": {}, "exporting": {}, "drilldown": {}, "navigation": {}, "legend": {"enabled": true}};
            var data = [{"data": [1475, 8363, 10457, 755, 945, 674, 208, 361, 523, 359], "type": "line", "name": "Series 1"}];
            option.series = data;
            var chart = new Highcharts.Chart(option);

    });
        </script>

    </body>

<h3><b>
 <p align="center"> Top 10 hashtags used in all the tweets were found out by using nltk in python. Hashtags such as #hillary,#clinton were counted as one. </p>
</b>
</h3>


</body>

<body>
	<style>
      body {
        font-family: 'Cormorant Upright', serif;
        font-size: 20px;
      }
    </style>
</body>

</html>

elections/templates/elections/home.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Averia+Libre|Cormorant+Upright" rel="stylesheet" >
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <title>Home</title>
</head>
<body>
<link rel="stylesheet" type="text/css" href="{% static 'elections/style.css' %}" />  <!--for background image-->
</body>
    <nav class="navbar navbar-inverse">
<div class="container-fluid">

<!--Header-->
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand mb-0">
  <img src="http://vignette4.wikia.nocookie.net/simpsons/images/1/11/Twitter_bird_icon.png/revision/latest?cb=20111228065136" width="50" height="40" class="d-inline-block align-top" alt="Twitter">
      #USElections2016
      </a>
<!--ITEMS-->

<div class="collapse navbar-collapse" id="topNavBar">
	<ul class="nav navbar-nav navbar-right">
			<li class="">
					<a href="{% url 'elections:analysis' %}">View Analysis
						<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&nbsp
					</a>
			</li>


	</ul>
</div>
</div>
</nav>
</body>

<body>
	<style>
      body {
        font-family: 'Cormorant Upright', serif;
        font-size: 30px;
      }
    </style>
</body>
</html>

elections/templates/elections/location.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8" />
     {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Averia+Libre|Cormorant+Upright" rel="stylesheet" >
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
    <link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
	<title>Location</title>

    <style>
      body {
        font-family: 'Cormorant Upright', serif;
        font-size: 20px;}
         #map { position:absolute; top:0px; bottom:0; width:100%; }

    </style>
</head>

<body >
<link rel="stylesheet" type="text/css" href="{% static 'elections/style2.css' %}" />

<nav class="navbar navbar-inverse">
<nav class="container-fluid">

<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand mb-0">
  <img src="http://vignette4.wikia.nocookie.net/simpsons/images/1/11/Twitter_bird_icon.png/revision/latest?cb=20111228065136" width="50" height="40" class="d-inline-block align-top" alt="Twitter">
      #USElections2016
      </a>

<div class="collapse navbar-collapse" id="topNavBar">
	<ul class="nav navbar-nav navbar-right">
			<li class="">
					<a href="{% url 'elections:analysis' %}">Back
						<span class="glyphicon glyphicon-hand-left" aria-hidden="true"></span>&nbsp
					</a>
			</li>

			<li class="">
					<a href="{% url 'elections:home' %}">Home
						<span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp
					</a>
			</li>
	</ul>
</div>
</nav>
</div>
</nav>
    </nav>

<div id='map'></div>
<script>
L.mapbox.accessToken = 'pk.eyJ1IjoicGd3b2RlaG91c2UiLCJhIjoiY2l1YTViY3RoMDAwMzJ0cWx3aGJ0bjljZCJ9.wZYiVykELoPNHGv_Q7LBIQ';
var geojson = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -84.51194444,
          37.47472222
        ]
      },
      properties: {}
    },

    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          139.6996048,
          35.66015797
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -3.1819938,
          55.9393909
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -77.029,
          38.8991
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -84.51194444,
          37.47472222
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -84.51194444,
          37.47472222
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          1.38446988,
          50.06629885
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -77.029,
          38.8991
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -76.8873336,
          38.7666786
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -71.6829081,
          42.4167635
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -91.0156594,
          30.8657362
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -72.5288034,
          41.2882208
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -93.7569395,
          38.3657849
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -90.2257781,
          41.8157606
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -98.9673069,
          35.5156056
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -76.8983059,
          38.7651145
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -80.1395,
          26.1587
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -90.1846716,
          41.8573554
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -76.88239,
          38.76369
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -90.3217585,
          32.3415342
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -74.90989,
          40.6367682
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -76.8983059,
          38.7651145
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -90.3140986,
          32.3473122
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -88.9933965,
          36.6672813
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -91.0037482,
          30.8492489
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -76.89439,
          38.78309
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -72.5320006,
          41.2892651
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -76.88239,
          38.76369
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -76.87935,
          38.7504
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -90.1846716,
          41.8573554
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -78.3233325,
          34.9979453
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -93.7596924,
          38.3659072
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -80.183333,
          25.83
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -76.87935,
          38.7504
        ]
      },
        properties:{}
    },
    {
        type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -78.3233325,
          34.9979453
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -76.87935,
          38.7504
        ]
      },
        properties:{}
    },
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -76.88239,
          38.76369
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          -78.3233325,
          34.9979453
        ]
      },
        properties:{}
    },
    {
     type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [
          23.7033898,
          37.9610178
        ]
      },
        properties:{}
    }
  ]
};
var map = L.mapbox.map('map', 'mapbox.streets', {
  scrollWheelZoom: false
}).setView([23.074343,-29.179688], 3);

var myLayer;
myLayer = L.mapbox.featureLayer(geojson, {
    pointToLayer: function (feature, latlon) {
        return L.circleMarker(latlon, {
            fillColor: '#ff0000',
            fillOpacity: 0.8,
            stroke: true
        });
    }
}).addTo(map);
</script>
</body>
</html>

elections/templates/elections/popularity.html
<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8" />
     {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Averia+Libre|Cormorant+Upright" rel="stylesheet" >
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

        <link href="https://www.highcharts.com/highslide/highslide.css" rel="stylesheet" />
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/highcharts-more.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/modules/heatmap.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/modules/exporting.js"></script>

	<title>Popularity</title>
</head>

<body >
<link rel="stylesheet" type="text/css" href="{% static 'elections/style2.css' %}" />

<nav class="navbar navbar-inverse">
<div class="container-fluid">

<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand mb-0">
  <img src="http://vignette4.wikia.nocookie.net/simpsons/images/1/11/Twitter_bird_icon.png/revision/latest?cb=20111228065136" width="50" height="40" class="d-inline-block align-top" alt="Twitter">
      #USElections2016
      </a>

<div class="collapse navbar-collapse" id="topNavBar">
	<ul class="nav navbar-nav navbar-right">
			<li class="">
					<a href="{% url 'elections:analysis' %}">Back
						<span class="glyphicon glyphicon-hand-left" aria-hidden="true"></span>&nbsp
					</a>
			</li>

			<li class="">
					<a href="{% url 'elections:home' %}">Home
						<span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp
					</a>
			</li>
	</ul>
</div>
</div>
</div>
</nav>
</body>

<body style="margin:0;padding:0">
                <div id="container" style="">Loading....</div>
<!--chart code-->
 <script>
        $(function(){
            Highcharts.setOptions({"lang": {}, "global": {}});
            var option = {"loading": {}, "subtitle": {}, "xAxis": {"categories": ["Donald Trump", "Hillary Clinton"]}, "title": {"text": "Popularity"}, "series": {}, "labels": {}, "chart": {"renderTo": "container", "type": "bar"}, "tooltip": {}, "plotOptions": {}, "yAxis": {"title": {"text": "Number of hashtags"}}, "credits": {"enabled": false}, "colors": {}, "pane": {}, "exporting": {}, "drilldown": {}, "navigation": {}, "legend": {"enabled": true}};
            var data = [{"data": [8363, 10457], "type": "bar", "name": "Series 1"}];
            option.series = data;
            var chart = new Highcharts.Chart(option);

    });
        </script>
<!--chart code ends-->


<h3><b>
 <p align="center"> Popularity of Donald Trump and Hillary Clinton is found out using hashtags. The person with more number of hashtags is considered more popular among the people. </p>
</b>
</h3>


</body>

<body>
	<style>
      body {
        font-family: 'Cormorant Upright', serif;
        font-size: 20px;
      }
    </style>
</body>
</html>

elections/templates/elections/retweets.html
<!DOCTYPE html>
<html>
<head>
     {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Averia+Libre|Cormorant+Upright" rel="stylesheet" >
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="https://www.highcharts.com/highslide/highslide.css" rel="stylesheet" />
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/highcharts-more.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/modules/heatmap.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/modules/exporting.js"></script>

	<title>Retweets</title>
</head>

<body>
<link rel="stylesheet" type="text/css" href="{% static 'elections/style2.css' %}" />

<nav class="navbar navbar-inverse">
<div class="container-fluid">
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand mb-0">
  <img src="http://vignette4.wikia.nocookie.net/simpsons/images/1/11/Twitter_bird_icon.png/revision/latest?cb=20111228065136" width="50" height="40" class="d-inline-block align-top" alt="Twitter">
      #USElections2016
      </a>

<div class="collapse navbar-collapse" id="topNavBar">
	<ul class="nav navbar-nav navbar-right">
			<li class="">
					<a href="{% url 'elections:analysis' %}">Back
						<span class="glyphicon glyphicon-hand-left" aria-hidden="true"></span>&nbsp
					</a>
			</li>

			<li class="">
					<a href="{% url 'elections:home' %}">Home
						<span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp
					</a>
			</li>
	</ul>
</div>
</div>
</div>
</nav>
</body>

 <body style="margin:0;padding:0">
                <div id="container" style="">Loading....</div>


    <script>
        $(function(){
            Highcharts.setOptions({"lang": {}, "global": {}});
            var option = {"loading": {}, "subtitle": {}, "xAxis": {}, "title": {"text": "Tweets Distribution"}, "series": {}, "labels": {}, "chart": {"renderTo": "container", "type": "pie"}, "tooltip": {}, "plotOptions": {}, "yAxis": {}, "credits": {"enabled": false}, "colors": {}, "pane": {}, "exporting": {}, "drilldown": {}, "navigation": {}, "legend": {"enabled": true}};
            var data = [{"data": [{"y": 9082, "name": "Original tweets"}, {"y": 13098, "name": "Retweets"}], "type": "pie", "name": "Series 1"}];
            option.series = data;
            var chart = new Highcharts.Chart(option);

    });
        </script>

    </body>
<h3><b>
 <p align="center"> Total tweets collected were 22180 out of which 13098 tweets were retweets and only 9082 original tweets were made.</p>
</b>
</h3>

</body>

<body>
	<style>
      body {
        font-family: 'Cormorant Upright', serif;
        font-size: 20px;
      }
    </style>
</body>
</html>